- hosts: all
  vars:
    logfile: /var/log/ansible.log
  tasks:
  - name: Create the cronjob.
    template:
      src=/srv/ansible/crontab.j2 dest=/etc/cron.d/ansible
      owner=root group=root mode=0644
    notify:
    - restart cron
  - name: Ensure logs are rotated.
    template:
      src=/srv/ansible/logrotate.j2 dest=/etc/logrotate.d/ansible
      owner=root group=root mode=0644
  handlers:
    - name: restart cron
      service: name=cron state=restarted

- hosts: mailservers
  vars:
    mailname: "{{ ansible_nodename }}.zwitterion.org"
  tasks:
  - name: ensure opensmtpd is installed.
    command:
      /srv/mail/install-opensmtpd
      creates=/usr/src/opensmtpd/installed
  - name: generate a certificate.
    command:
      /srv/mail/create-certificate
      creates=/etc/ssl/certs/{{ mailname }}.crt
  - name: generate a config.
    template:
      src=/srv/mail/smtpd.conf.j2 dest=/etc/smtpd.conf
      owner=root group=root mode=0644
      validate='smtpd -n -f %s'
    notify:
    - restart opensmtpd
  - name: ensure the service is running.
    service: name=opensmtpd state=started
  handlers:
    - name: restart opensmtpd
      service: name=opensmtpd state=restarted

- hosts: nameservers
  tasks:
  - name: ensure bind9 is at the latest version.
    apt: pkg=bind9 state=latest
  - name: get the list of zones.
    command: ls /srv/dns/zones
    register: zones
  - name: generate a config.
    template:
      src=/srv/dns/named.conf.j2 dest=/etc/bind/named.conf
      owner=root group=root mode=0644
      validate='named-checkconf %s'
    notify:
    - restart bind
  - name: ensure the service is running.
    service: name=bind9 state=started
  handlers:
    - name: restart bind
      service: name=bind9 state=restarted
