- hosts: nameservers
  tasks:
  - name: ensure bind9 is at the latest version.
    apt: pkg=bind9 state=latest
  - name: generate the configuration file.
    template:
      src=/srv/dns/named.conf.j2
      dest=/etc/bind/named.conf
      validate='named-checkconf %s'
