- hosts: mailservers

  vars:

    mailname: "{{ ansible_nodename }}.zwitterion.org"

  tasks:

    - name: ensure opensmtpd is installed.
      command:
        /srv/mail/install-opensmtpd
        creates=/usr/src/opensmtpd/installed

    - name: generate a certificate.
      command:
        /srv/mail/create-certificate
        creates=/etc/ssl/certs/{{ mailname }}.crt

    - name: create a new home for the tables.
      command:
        mkdir -p /etc/mail /srv/mail/tables
        creates=/etc/mail

    - name: pull tables from cloud storage.
      command: gsutil rsync gs://zwitterion-org-mail-tables/ /srv/mail/tables/

    - name: copy credentials into place.
      copy: src=/srv/mail/tables/credentials dest=/etc/mail/credentials
      notify:
      - rebuild credentials

    - name: copy forwarding into place.
      copy: src=/srv/mail/tables/forwarding dest=/etc/mail/forwarding
      notify:
      - rebuild forwarding

    - meta: flush_handlers

    - name: generate a config.
      template:
        src=/srv/mail/smtpd.conf.j2 dest=/etc/smtpd.conf
        owner=root group=root mode=0644
        validate='smtpd -n -f %s'
      notify:
      - restart opensmtpd

    - name: ensure the service is running.
      service: name=opensmtpd state=started

  handlers:

    - name: rebuild credentials
      command: makemap /etc/mail/credentials

    - name: rebuild forwarding
      command: makemap -t aliases /etc/mail/forwarding

    - name: restart opensmtpd
      service: name=opensmtpd state=restarted

