#!/bin/bash
# Ugly hack to install opensmtpd from jessie (it's not packaged for wheezy).

set -e
set -u

git clone git://anonscm.debian.org/collab-maint/opensmtpd.git /usr/src/opensmtpd/debian

cd /usr/src/opensmtpd/debian

apt-get install --yes build-essential
apt-get install --yes $( dpkg-checkbuilddeps |& cut -d : -f 3 | sed -e 's/([^)]*)//g' )

dpkg-buildpackage -b -uc -us

cd ..

DEBIAN_FRONTEND=noninteractive dpkg --install opensmtpd*.deb

rm opensmtpd*

touch installed
