#!/bin/bash

set -e
set -u

smtpctl log verbose
smtpctl trace expand
smtpctl trace smtp

(
  sleep 1
  echo 'ehlo localhost'
  sleep 1
  echo 'mail from:<suter@zwit.org>'
  sleep 1
  echo 'rcpt to:<suter-123@bob.zwit.org>'
  sleep 1
  echo 'rcpt to:<suter-456@tom.zwit.org>'
  sleep 1
  echo 'rcpt to:<other@someone.zwit.org>'
  sleep 1
  echo 'rcpt to:<other@zwitterion.org>'
  sleep 1
  echo 'rset'
  sleep 1
  echo 'quit'
  sleep 1
) | tee /dev/stderr | nc $(uname -n) smtp
